default: &default
  adapter: postgresql
  database: milieu
  username: adminshwtagq
  password: CepAPzQHR_aH
  host: localhost

development:
  <<: *default
  port: 5432

test:
  <<: *default

production:
  <<: *default
  port: 5432


  #   database: milieu-landing
  # username: postgres
  # password: postgres