default: &default
  adapter: postgresql
  database: milieu
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  port: 5432

test:
  <<: *default

production:
  <<: *default
  port: 5432


  #   database: milieu-landing
  # 

  # Root User: adminc6hpt3t
  #  Root Password: RrTA4qHwsYvD
  #  Database Name: milieu

  # username: adminshwtagq
  # password: CepAPzQHR_aH